# Header
menu:
  首页: /
  文章: /archives
  关于: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: true

# Sidebar
sidebar: right
widgets:
- recommend_posts
- links
- category
- tagcloud
- archive
- recent_comments

recommend_posts:
  Hello World —— TaoSama博客搭建历程: http://taosama.github.io/2016/03/09/Hello%20World%20%E2%80%94%E2%80%94%20%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E5%8E%86%E7%A8%8B/

# Links
links:
  我的CSDN: http://blog.csdn.net/xfzero/

  
# Miscellaneous
google_analytics:
favicon: logo.ico
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: zerolxf

# Baidu share
baidushare: true
